### ISSUE TITLE
Suggestion: Change title color

### ISSUE THREAD

**Issue by dummy-account2000** [Mantena-Projects/github-crash-course#1]
I think it looks better if the main title is a bit more orange.

The styling rule could be changed like this:

```css
h1 {
  color: #a58e54;
}
```
